import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1753911217499 implements MigrationInterface {
    name = 'InitialSchema1753911217499'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`rol\` CHANGE \`descripcion\` \`descripcion\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`asignacion\` CHANGE \`id_tarea\` \`id_tarea\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`asignacion\` CHANGE \`id_voluntario\` \`id_voluntario\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`asignacion\` CHANGE \`rol_asignado\` \`rol_asignado\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`tipo\` \`tipo\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`descripcion\` \`descripcion\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`cantidad\` \`cantidad\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`monto\` \`monto\` decimal(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`fecha\` \`fecha\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`id_proyecto\` \`id_proyecto\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`descripcion\` \`descripcion\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`fecha_inicio\` \`fecha_inicio\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`fecha_fin\` \`fecha_fin\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`id_estado\` \`id_estado\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`id_fase\` \`id_fase\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fase\` CHANGE \`nombre\` \`nombre\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fase\` CHANGE \`descripcion\` \`descripcion\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fase\` CHANGE \`orden\` \`orden\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fase\` CHANGE \`id_proyecto\` \`id_proyecto\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` CHANGE \`id_donacion\` \`id_donacion\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` CHANGE \`id_proyecto\` \`id_proyecto\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` CHANGE \`monto_asignado\` \`monto_asignado\` decimal(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reporte\` CHANGE \`tipo\` \`tipo\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reporte\` CHANGE \`fecha\` \`fecha\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reporte\` CHANGE \`contenido\` \`contenido\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reporte\` CHANGE \`id_proyecto\` \`id_proyecto\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`nombre\` \`nombre\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`descripcion\` \`descripcion\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`objetivo\` \`objetivo\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`ubicacion\` \`ubicacion\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`fecha_inicio\` \`fecha_inicio\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`fecha_fin\` \`fecha_fin\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`id_estado\` \`id_estado\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`estado\` CHANGE \`nombre\` \`nombre\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion\` CHANGE \`id_organizacion\` \`id_organizacion\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion\` CHANGE \`monto_total\` \`monto_total\` decimal(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion\` CHANGE \`fecha\` \`fecha\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion\` CHANGE \`condiciones\` \`condiciones\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`id_usuario\` \`id_usuario\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` ADD UNIQUE INDEX \`IDX_a434fef9deb7d92b1120e93cde\` (\`id_usuario\`)`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`nombre\` \`nombre\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`tipo\` \`tipo\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`sitio_web\` \`sitio_web\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`pais\` \`pais\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`ciudad\` \`ciudad\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`areas_enfoque\` \`areas_enfoque\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`mision_vision\` \`mision_vision\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` CHANGE \`nombre\` \`nombre\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`correo\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`correo\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD UNIQUE INDEX \`IDX_349ecb64acc4355db443ca17cb\` (\`correo\`)`);
        await queryRunner.query(`ALTER TABLE \`usuario\` CHANGE \`id_rol\` \`id_rol\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`jornada\` CHANGE \`nombre\` \`nombre\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` CHANGE \`id_usuario\` \`id_usuario\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` ADD UNIQUE INDEX \`IDX_b9ff2b8aec5d19e99083c75fd3\` (\`id_usuario\`)`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` CHANGE \`id_jornada\` \`id_jornada\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` CHANGE \`id_estado\` \`id_estado\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` CHANGE \`disponibilidad\` \`disponibilidad\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`habilidad\` CHANGE \`nombre\` \`nombre\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`habilidad\` CHANGE \`descripcion\` \`descripcion\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario_habilidad\` CHANGE \`tiempo_experiencia\` \`tiempo_experiencia\` varchar(50) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_a434fef9deb7d92b1120e93cde\` ON \`organizacion\` (\`id_usuario\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_b9ff2b8aec5d19e99083c75fd3\` ON \`voluntario\` (\`id_usuario\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1d9e5be3d74310f98e398912d9\` ON \`rol_permiso\` (\`id_rol\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9c0fd212b970f71bf0a9465c4f\` ON \`rol_permiso\` (\`id_permiso\`)`);
        await queryRunner.query(`ALTER TABLE \`asignacion\` ADD CONSTRAINT \`FK_080b54e04105cbc5e51f9f12761\` FOREIGN KEY (\`id_tarea\`) REFERENCES \`tarea\`(\`id_tarea\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`asignacion\` ADD CONSTRAINT \`FK_ff6c9d81e95011500e2926e06f9\` FOREIGN KEY (\`id_voluntario\`) REFERENCES \`voluntario\`(\`id_voluntario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` ADD CONSTRAINT \`FK_6c9de691fff88546d526c0be721\` FOREIGN KEY (\`id_proyecto\`) REFERENCES \`proyecto\`(\`id_proyecto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` ADD CONSTRAINT \`FK_a2cc74e37019249efd3b9274186\` FOREIGN KEY (\`id_tarea\`) REFERENCES \`tarea\`(\`id_tarea\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` ADD CONSTRAINT \`FK_f798af7984d221fbe8b402e0b83\` FOREIGN KEY (\`id_donacion\`) REFERENCES \`donacion\`(\`id_donacion\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tarea\` ADD CONSTRAINT \`FK_48eeaaf81750df62901889574e7\` FOREIGN KEY (\`id_estado\`) REFERENCES \`estado\`(\`id_estado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tarea\` ADD CONSTRAINT \`FK_271445314b408ec9ec3c19d9e66\` FOREIGN KEY (\`id_fase\`) REFERENCES \`fase\`(\`id_fase\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fase\` ADD CONSTRAINT \`FK_6e6cf7e6c950bcb2f99632a20f5\` FOREIGN KEY (\`id_proyecto\`) REFERENCES \`proyecto\`(\`id_proyecto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` ADD CONSTRAINT \`FK_d7153b581a96292cfa38cc29b69\` FOREIGN KEY (\`id_donacion\`) REFERENCES \`donacion\`(\`id_donacion\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` ADD CONSTRAINT \`FK_e8fc3410eb6a8b322569e38c710\` FOREIGN KEY (\`id_proyecto\`) REFERENCES \`proyecto\`(\`id_proyecto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reporte\` ADD CONSTRAINT \`FK_aca7331dcd0e2cee6e92b29408e\` FOREIGN KEY (\`id_proyecto\`) REFERENCES \`proyecto\`(\`id_proyecto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evaluacion\` ADD CONSTRAINT \`FK_7b335b72565eb886d680c6feb37\` FOREIGN KEY (\`id_voluntario\`) REFERENCES \`voluntario\`(\`id_voluntario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evaluacion\` ADD CONSTRAINT \`FK_4c414d056233bda67d28e860031\` FOREIGN KEY (\`id_proyecto\`) REFERENCES \`proyecto\`(\`id_proyecto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` ADD CONSTRAINT \`FK_5dc5ddea3fd8edda48a6d5e94c1\` FOREIGN KEY (\`id_estado\`) REFERENCES \`estado\`(\`id_estado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`donacion\` ADD CONSTRAINT \`FK_95617e4c45e5efa3331b60881e2\` FOREIGN KEY (\`id_organizacion\`) REFERENCES \`organizacion\`(\`id_organizacion\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`donacion\` ADD CONSTRAINT \`FK_981d4a4f7835f640c5181b9909d\` FOREIGN KEY (\`id_metodo\`) REFERENCES \`metodopago\`(\`id_metodo\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`donacion\` ADD CONSTRAINT \`FK_a5bdd9db938385e5caf9c9badde\` FOREIGN KEY (\`id_estado\`) REFERENCES \`estado\`(\`id_estado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` ADD CONSTRAINT \`FK_a434fef9deb7d92b1120e93cde7\` FOREIGN KEY (\`id_usuario\`) REFERENCES \`usuario\`(\`id_usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD CONSTRAINT \`FK_3628e9894c4b014d61a01cb21dd\` FOREIGN KEY (\`id_rol\`) REFERENCES \`rol\`(\`id_rol\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disponibilidad\` ADD CONSTRAINT \`FK_f35e270b26165db42c39b0b2069\` FOREIGN KEY (\`id_voluntario\`) REFERENCES \`voluntario\`(\`id_voluntario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` ADD CONSTRAINT \`FK_b9ff2b8aec5d19e99083c75fd3e\` FOREIGN KEY (\`id_usuario\`) REFERENCES \`usuario\`(\`id_usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` ADD CONSTRAINT \`FK_ba654756ea424a96a61b0f6c42b\` FOREIGN KEY (\`id_jornada\`) REFERENCES \`jornada\`(\`id_jornada\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` ADD CONSTRAINT \`FK_40b4a17baae6b4f06b6447f64a7\` FOREIGN KEY (\`id_estado\`) REFERENCES \`estado\`(\`id_estado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`voluntario_habilidad\` ADD CONSTRAINT \`FK_ea071f223de95d33382af5856a5\` FOREIGN KEY (\`id_voluntario\`) REFERENCES \`voluntario\`(\`id_voluntario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`voluntario_habilidad\` ADD CONSTRAINT \`FK_d1817a82c45d7ee2156b5126c2d\` FOREIGN KEY (\`id_habilidad\`) REFERENCES \`habilidad\`(\`id_habilidad\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rol_permiso\` ADD CONSTRAINT \`FK_1d9e5be3d74310f98e398912d94\` FOREIGN KEY (\`id_rol\`) REFERENCES \`rol\`(\`id_rol\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rol_permiso\` ADD CONSTRAINT \`FK_9c0fd212b970f71bf0a9465c4f3\` FOREIGN KEY (\`id_permiso\`) REFERENCES \`permiso\`(\`id_permiso\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`rol_permiso\` DROP FOREIGN KEY \`FK_9c0fd212b970f71bf0a9465c4f3\``);
        await queryRunner.query(`ALTER TABLE \`rol_permiso\` DROP FOREIGN KEY \`FK_1d9e5be3d74310f98e398912d94\``);
        await queryRunner.query(`ALTER TABLE \`voluntario_habilidad\` DROP FOREIGN KEY \`FK_d1817a82c45d7ee2156b5126c2d\``);
        await queryRunner.query(`ALTER TABLE \`voluntario_habilidad\` DROP FOREIGN KEY \`FK_ea071f223de95d33382af5856a5\``);
        await queryRunner.query(`ALTER TABLE \`voluntario\` DROP FOREIGN KEY \`FK_40b4a17baae6b4f06b6447f64a7\``);
        await queryRunner.query(`ALTER TABLE \`voluntario\` DROP FOREIGN KEY \`FK_ba654756ea424a96a61b0f6c42b\``);
        await queryRunner.query(`ALTER TABLE \`voluntario\` DROP FOREIGN KEY \`FK_b9ff2b8aec5d19e99083c75fd3e\``);
        await queryRunner.query(`ALTER TABLE \`disponibilidad\` DROP FOREIGN KEY \`FK_f35e270b26165db42c39b0b2069\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP FOREIGN KEY \`FK_3628e9894c4b014d61a01cb21dd\``);
        await queryRunner.query(`ALTER TABLE \`organizacion\` DROP FOREIGN KEY \`FK_a434fef9deb7d92b1120e93cde7\``);
        await queryRunner.query(`ALTER TABLE \`donacion\` DROP FOREIGN KEY \`FK_a5bdd9db938385e5caf9c9badde\``);
        await queryRunner.query(`ALTER TABLE \`donacion\` DROP FOREIGN KEY \`FK_981d4a4f7835f640c5181b9909d\``);
        await queryRunner.query(`ALTER TABLE \`donacion\` DROP FOREIGN KEY \`FK_95617e4c45e5efa3331b60881e2\``);
        await queryRunner.query(`ALTER TABLE \`proyecto\` DROP FOREIGN KEY \`FK_5dc5ddea3fd8edda48a6d5e94c1\``);
        await queryRunner.query(`ALTER TABLE \`evaluacion\` DROP FOREIGN KEY \`FK_4c414d056233bda67d28e860031\``);
        await queryRunner.query(`ALTER TABLE \`evaluacion\` DROP FOREIGN KEY \`FK_7b335b72565eb886d680c6feb37\``);
        await queryRunner.query(`ALTER TABLE \`reporte\` DROP FOREIGN KEY \`FK_aca7331dcd0e2cee6e92b29408e\``);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` DROP FOREIGN KEY \`FK_e8fc3410eb6a8b322569e38c710\``);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` DROP FOREIGN KEY \`FK_d7153b581a96292cfa38cc29b69\``);
        await queryRunner.query(`ALTER TABLE \`fase\` DROP FOREIGN KEY \`FK_6e6cf7e6c950bcb2f99632a20f5\``);
        await queryRunner.query(`ALTER TABLE \`tarea\` DROP FOREIGN KEY \`FK_271445314b408ec9ec3c19d9e66\``);
        await queryRunner.query(`ALTER TABLE \`tarea\` DROP FOREIGN KEY \`FK_48eeaaf81750df62901889574e7\``);
        await queryRunner.query(`ALTER TABLE \`movimiento\` DROP FOREIGN KEY \`FK_f798af7984d221fbe8b402e0b83\``);
        await queryRunner.query(`ALTER TABLE \`movimiento\` DROP FOREIGN KEY \`FK_a2cc74e37019249efd3b9274186\``);
        await queryRunner.query(`ALTER TABLE \`movimiento\` DROP FOREIGN KEY \`FK_6c9de691fff88546d526c0be721\``);
        await queryRunner.query(`ALTER TABLE \`asignacion\` DROP FOREIGN KEY \`FK_ff6c9d81e95011500e2926e06f9\``);
        await queryRunner.query(`ALTER TABLE \`asignacion\` DROP FOREIGN KEY \`FK_080b54e04105cbc5e51f9f12761\``);
        await queryRunner.query(`DROP INDEX \`IDX_9c0fd212b970f71bf0a9465c4f\` ON \`rol_permiso\``);
        await queryRunner.query(`DROP INDEX \`IDX_1d9e5be3d74310f98e398912d9\` ON \`rol_permiso\``);
        await queryRunner.query(`DROP INDEX \`REL_b9ff2b8aec5d19e99083c75fd3\` ON \`voluntario\``);
        await queryRunner.query(`DROP INDEX \`REL_a434fef9deb7d92b1120e93cde\` ON \`organizacion\``);
        await queryRunner.query(`ALTER TABLE \`voluntario_habilidad\` CHANGE \`tiempo_experiencia\` \`tiempo_experiencia\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`habilidad\` CHANGE \`descripcion\` \`descripcion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`habilidad\` CHANGE \`nombre\` \`nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` CHANGE \`disponibilidad\` \`disponibilidad\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` CHANGE \`id_jornada\` \`id_jornada\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`voluntario\` DROP INDEX \`IDX_b9ff2b8aec5d19e99083c75fd3\``);
        await queryRunner.query(`ALTER TABLE \`voluntario\` CHANGE \`id_usuario\` \`id_usuario\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`jornada\` CHANGE \`nombre\` \`nombre\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` CHANGE \`id_rol\` \`id_rol\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP INDEX \`IDX_349ecb64acc4355db443ca17cb\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`correo\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`correo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` CHANGE \`nombre\` \`nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`mision_vision\` \`mision_vision\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`areas_enfoque\` \`areas_enfoque\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`ciudad\` \`ciudad\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`pais\` \`pais\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`sitio_web\` \`sitio_web\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`tipo\` \`tipo\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`nombre\` \`nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizacion\` DROP INDEX \`IDX_a434fef9deb7d92b1120e93cde\``);
        await queryRunner.query(`ALTER TABLE \`organizacion\` CHANGE \`id_usuario\` \`id_usuario\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion\` CHANGE \`condiciones\` \`condiciones\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion\` CHANGE \`fecha\` \`fecha\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion\` CHANGE \`monto_total\` \`monto_total\` decimal(12,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion\` CHANGE \`id_organizacion\` \`id_organizacion\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`estado\` CHANGE \`nombre\` \`nombre\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`fecha_fin\` \`fecha_fin\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`fecha_inicio\` \`fecha_inicio\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`ubicacion\` \`ubicacion\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`objetivo\` \`objetivo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`descripcion\` \`descripcion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`proyecto\` CHANGE \`nombre\` \`nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`reporte\` CHANGE \`id_proyecto\` \`id_proyecto\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reporte\` CHANGE \`contenido\` \`contenido\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reporte\` CHANGE \`fecha\` \`fecha\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`reporte\` CHANGE \`tipo\` \`tipo\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` CHANGE \`monto_asignado\` \`monto_asignado\` decimal(12,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` CHANGE \`id_proyecto\` \`id_proyecto\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`donacion_proyecto\` CHANGE \`id_donacion\` \`id_donacion\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fase\` CHANGE \`id_proyecto\` \`id_proyecto\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fase\` CHANGE \`orden\` \`orden\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fase\` CHANGE \`descripcion\` \`descripcion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`fase\` CHANGE \`nombre\` \`nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`id_fase\` \`id_fase\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`fecha_fin\` \`fecha_fin\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`fecha_inicio\` \`fecha_inicio\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tarea\` CHANGE \`descripcion\` \`descripcion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`id_proyecto\` \`id_proyecto\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`fecha\` \`fecha\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`monto\` \`monto\` decimal(12,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`cantidad\` \`cantidad\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`descripcion\` \`descripcion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`movimiento\` CHANGE \`tipo\` \`tipo\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`asignacion\` CHANGE \`rol_asignado\` \`rol_asignado\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`asignacion\` CHANGE \`id_voluntario\` \`id_voluntario\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`asignacion\` CHANGE \`id_tarea\` \`id_tarea\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rol\` CHANGE \`descripcion\` \`descripcion\` varchar(255) NULL`);
    }

}
